const test = require("node:test"), assert = require("node:assert/strict"), crypto = require("node:crypto"), fs = require("node:fs"), path = require("node:path"), http = require("node:http");
const { Sequelize } = require("sequelize"), { Umzug, SequelizeStorage } = require("umzug"), express = require("express"), jwt = require("jsonwebtoken");
test("Daily logs and weekly mentor review: guarded PostgreSQL and authenticated HTTP", { skip: !process.env.INTERNSHIP_LOG_DISPOSABLE_DATABASE_URL }, async t => {
  const db = new Sequelize(process.env.INTERNSHIP_LOG_DISPOSABLE_DATABASE_URL, { logging: false, pool: { max: 8 } }); let server;
  try {
    const [[guard]] = await db.query("SELECT current_database() AS db,current_setting('fitm.a018_disposable',true) AS marker"); assert.equal(guard.db, "fitm_logs_test"); assert.equal(guard.marker, "on");
    const m = { sequelize: db }; for (const file of fs.readdirSync(path.join(__dirname, "../src/models")).filter(f => f.endsWith(".model.js"))) { const model = require(`../src/models/${file}`)(db); m[model.name] = model; } for (const model of Object.values(m)) model.associate?.(m);
    const umzug = new Umzug({ migrations: { glob: ["*.js", { cwd: path.join(__dirname, "../src/db/migrations") }] }, context: db.getQueryInterface(), storage: new SequelizeStorage({ sequelize: db, tableName: "sequelize_meta" }), logger: undefined });
    await umzug.up({ to: "017_add_company_responses.js" }); const migration = require("../src/db/migrations/018_add_internship_logs");
    await t.test("018 empty up/down/reapply preserves existing file fingerprint", async () => {
      const fingerprint = async () => (await db.query("SELECT md5(COALESCE(string_agg(to_jsonb(t)::text,'' ORDER BY id),'')) AS f FROM student_files t"))[0][0].f;
      const before = await fingerprint(); await migration.up({ context: db.getQueryInterface() }); await migration.down({ context: db.getQueryInterface() });
      const originalQuery = db.query;
      db.query = function (sql, options) { return originalQuery.call(this, typeof sql === "string" && sql.includes("CREATE TABLE internship_daily_logs") ? sql + " SELECT missing_018_test_function();" : sql, options); };
      try { await assert.rejects(migration.up({ context: db.getQueryInterface() }), /missing_018_test_function/); } finally { db.query = originalQuery; }
      assert.equal((await db.query("SELECT to_regclass('internship_daily_logs') AS name"))[0][0].name, null);
      await umzug.up(); assert.equal((await umzug.executed()).length, 22); assert.equal(await fingerprint(), before);
    });
    const run = crypto.randomUUID().slice(0, 8), password = crypto.randomBytes(24).toString("hex");
    const a = await m.Student.create({ student_id: `logs-a-${run}`, email: `logs-a-${run}@email.kmutnb.ac.th`, first_name: "นักศึกษา", last_name: "เอ", major: "INE", track: "co_op", password });
    const b = await m.Student.create({ student_id: `logs-b-${run}`, email: `logs-b-${run}@email.kmutnb.ac.th`, first_name: "นักศึกษา", last_name: "บี", major: "INE", track: "co_op", password });
    const requestData = owner => ({ student_id: owner.id, company_name: "Disposable company", company_province: "กรุงเทพมหานคร", company_address: "Fixture address", letter_recipient_name: "Fixture", work_start_date: "2026-09-23", work_end_date: "2026-10-08", status: "approved" });
    const requestA = await m.CoopRequest.create(requestData(a)); await m.CoopRequest.create(requestData(b));
    const mentor = await m.Mentor.create({ student_id: a.id, first_name: "พี่เลี้ยง", last_name: "เอ", position: "Fixture", email: `${run}@fixture.invalid`, status: "verified", verified_at: new Date() });
    let delivery, failEmail = false; const app = express(); app.use(express.json()); app.use("/api/internship-logs", require("../src/routes/internshipLogs.routes").createInternshipLogsRouter({ models: m, sendEmail: async value => { delivery = value; if (failEmail) throw Error("Fixture delivery failed"); } }));
    server = http.createServer(app); await new Promise(resolve => server.listen(0, "127.0.0.1", resolve)); const base = `http://127.0.0.1:${server.address().port}/api/internship-logs`;
    const auth = owner => jwt.sign({ id: owner.id, student_id: owner.student_id, actor_type: "student", role: "student" }, process.env.JWT_SECRET, { expiresIn: "10m" });
    const call = async (url, method = "GET", body, token = auth(a)) => { const response = await fetch(base + url, { method, headers: { ...(token && { Authorization: `Bearer ${token}` }), ...(body !== undefined && { "Content-Type": "application/json" }) }, ...(body !== undefined && { body: JSON.stringify(body) }) }); return { status: response.status, body: await response.json() }; };
    const work = { kind: "working", assigned_work: "พัฒนาระบบ", work_result: "ทดสอบผ่าน", problems: "ไม่มีปัญหา", solutions: "ไม่ต้องแก้ไข", notes: "" };
    const service = require("../src/services/internshipLog.service").createInternshipLogService(m, { now: () => new Date("2026-10-08T12:00:00+07:00") });
    const overview = () => call("/overview?date=2026-09-23"); let first, weekId, access;
    await t.test("missing days and first partial week derive actual approved internship", async () => { const result = await overview(); assert.equal(result.status, 200); assert.deepEqual(result.body.required_dates, ["2026-09-23", "2026-09-24", "2026-09-25", "2026-09-26", "2026-09-27"]); assert.equal(result.body.missing_dates.length, 5); assert.equal(result.body.total_logs, 0); });
    await t.test("daily create/read/update persists one owner/date and allows no problems", async () => { let result = await call("/days/2026-09-23", "POST", work); assert.equal(result.status, 201); first = result.body.log; assert.equal(first.problems, "ไม่มีปัญหา"); result = await call("/days/2026-09-23", "PUT", { ...work, version: 1, notes: "เพิ่มเติม" }); assert.equal(result.status, 200); assert.equal(result.body.log.version, 2); assert.equal((await call("/days/2026-09-23")).body.log.notes, "เพิ่มเติม"); });
    await t.test("duplicate creates and stale concurrent edits do not lose data", async () => { assert.equal((await call("/days/2026-09-23", "POST", work)).status, 409); const results = await Promise.all([call("/days/2026-09-23", "PUT", { ...work, version: 2, notes: "A" }), call("/days/2026-09-23", "PUT", { ...work, version: 2, notes: "B" })]); assert.deepEqual(results.map(r => r.status).sort(), [200, 409]); assert.equal(await m.InternshipDailyLog.count(), 1); });
    await t.test("ownership, authentication and role spoofing are rejected", async () => { assert.equal((await call("/days/2026-09-23", "GET", undefined, auth(b))).body.log, null); assert.equal((await call("/days/2026-09-23", "PUT", { ...work, version: 3 }, auth(b))).status, 404); assert.equal((await call("/overview", "GET", undefined, null)).status, 401); for (const role of ["teacher", "department_staff", "department_head"]) assert.equal((await call("/overview", "GET", undefined, jwt.sign({ id: a.id, student_id: a.student_id, role }, process.env.JWT_SECRET))).status, 403); assert.equal((await call("/days/2026-09-24", "POST", { ...work, student_id: b.id })).status, 400); });
    await t.test("invalid/future/outside dates and incomplete contents do not create logs", async () => { for (const d of ["2026-13-01", "2026-02-30", "2026-09-22"]) assert.equal((await call(`/days/${d}`, "POST", work)).status, 400); await assert.rejects(service.save(a.id, "2026-10-09", work, true), e => e.code === "FUTURE_DATE"); assert.equal((await call("/days/2026-09-24", "POST", { ...work, assigned_work: "" })).status, 400); assert.equal(await m.InternshipDailyLog.count(), 1); });
    await t.test("missing-day submission explains omissions and verified Mentor required", async () => { const result = await call("/weeks/2026-09-21/submit", "POST", { version: 0 }); assert.equal(result.status, 400); assert.equal(result.body.missing_dates.length, 4); assert.equal((await call("/weeks/2026-09-21/submit", "POST", { version: 0 }, auth(b))).body.code, "VERIFIED_MENTOR_REQUIRED"); });
    await t.test("nonworking holidays/leave count without creating fictional work", async () => { for (const d of ["2026-09-24", "2026-09-25"]) assert.equal((await call(`/days/${d}`, "POST", work)).status, 201); for (const d of ["2026-09-26", "2026-09-27"]) assert.equal((await call(`/days/${d}`, "POST", { kind: "non_working", non_working_reason: "วันหยุด" })).status, 201); assert.equal((await overview()).body.missing_dates.length, 0); });
    await t.test("concurrent weekly submit commits one immutable snapshot/event/token", async () => { const result = await Promise.all([call("/weeks/2026-09-21/submit", "POST", { version: 0 }), call("/weeks/2026-09-21/submit", "POST", { version: 0 })]); assert.deepEqual(result.map(r => r.status).sort(), [200, 409]); const saved = result.find(r => r.status === 200); weekId = saved.body.submission.id; access = delivery.token; assert.equal(saved.body.submission.snapshot.logs.length, 5); assert.equal(await m.InternshipWeekEvent.count(), 1); assert.equal(await m.InternshipReviewToken.count(), 1); assert.ok(!JSON.stringify(saved.body).includes(access)); assert.notEqual((await m.InternshipReviewToken.findOne()).token_hash, access); });
    await t.test("submitted logs freeze in API and SQL; immutable events and rollback refusal", async () => { assert.equal((await call("/days/2026-09-23", "PUT", { ...work, version: 3 })).body.code, "LOG_FROZEN"); await assert.rejects(db.query("UPDATE internship_daily_logs SET notes='overwrite'"), /frozen/); await assert.rejects(db.query("UPDATE internship_week_events SET feedback='overwrite'"), /immutable/); await assert.rejects(db.query("DELETE FROM internship_week_events"), /immutable/); await assert.rejects(migration.down({ context: db.getQueryInterface() }), /populated/); });
    await t.test("mentor scope hides other students, rejects anonymous/verification/expired tokens", async () => { assert.equal((await call("/mentor/weeks", "GET", undefined, null)).status, 401); assert.equal((await call("/mentor/weeks", "GET", undefined, crypto.randomBytes(32).toString("hex"))).status, 401); assert.equal((await call("/mentor/weeks", "GET", undefined, access)).body.weeks.length, 1); assert.equal((await call(`/mentor/weeks/${crypto.randomUUID()}`, "GET", undefined, access)).status, 404); await m.InternshipReviewToken.update({ expires_at: new Date(0) }, { where: {} }); assert.equal((await call("/mentor/weeks", "GET", undefined, access)).status, 410); await call("/mentor-link", "POST", {}); access = delivery.token; });
    await t.test("revision requests require feedback and preserve daily/snapshot history", async () => { assert.equal((await call(`/mentor/weeks/${weekId}/review`, "POST", { action: "revision_requested", version: 1, feedback: "" }, access)).status, 400); assert.equal((await call(`/mentor/weeks/${weekId}/review`, "POST", { action: "revision_requested", version: 1, feedback: "เพิ่มรายละเอียดผลการทำงาน" }, access)).status, 200); assert.equal((await overview()).body.history.at(-1).mentor_name, "พี่เลี้ยง เอ"); assert.equal((await call("/days/2026-09-23", "PUT", { ...work, version: 3, work_result: "ผลที่แก้ไขแล้ว" })).status, 200); assert.equal((await overview()).body.history[0].snapshot.logs[0].work_result, "ทดสอบผ่าน"); });
    await t.test("resubmit snapshots changed records, locks again and keeps revisions", async () => { assert.equal((await call("/weeks/2026-09-21/submit", "POST", { version: 1 })).status, 409); assert.equal((await call("/weeks/2026-09-21/submit", "POST", { version: 2 })).status, 200); const result = (await overview()).body; assert.equal(result.submission.version, 3); assert.equal(result.history.length, 3); assert.equal(result.submission.snapshot.logs[0].work_result, "ผลที่แก้ไขแล้ว"); assert.equal((await call("/mentor/weeks", "GET", undefined, access)).status, 410); access = delivery.token; });
    await t.test("duplicate/concurrent Mentor review commits one final feedback event", async () => { const results = await Promise.all([call(`/mentor/weeks/${weekId}/review`, "POST", { version: 3, action: "reviewed", feedback: "ดีมาก" }, access), call(`/mentor/weeks/${weekId}/review`, "POST", { version: 3, action: "reviewed", feedback: "duplicate" }, access)]); assert.deepEqual(results.map(r => r.status).sort(), [200, 409]); const result = (await overview()).body; assert.equal(result.history.length, 4); assert.equal(result.submission.status, "reviewed"); assert.equal(result.history.at(-1).mentor_id, mentor.id); assert.equal((await call("/days/2026-09-23", "PUT", { ...work, version: 4 })).status, 409); });
    await t.test("mentor pending/reverification revokes token through live relationship checks", async () => { const stamp = mentor.verified_at; await mentor.update({ status: "pending" }); assert.equal((await call("/mentor/weeks", "GET", undefined, access)).status, 403); await mentor.update({ status: "verified", verified_at: new Date(Date.now() + 1000) }); assert.equal((await call("/mentor/weeks", "GET", undefined, access)).status, 403); await mentor.update({ verified_at: stamp }); });
    await t.test("a real verified foreign Mentor capability cannot read or review another Student", async () => {
      const foreignData = { student_id: b.id, first_name: "Other", last_name: "Mentor", position: "Fixture", email: `foreign-${run}@fixture.invalid`, status: "verified", verified_at: new Date() };
      const foreignMentor = await m.Mentor.create(foreignData);
      const foreignAccess = (await service.resend(b.id)).token;
      assert.equal((await call(`/mentor/weeks/${weekId}`, "GET", undefined, foreignAccess)).status, 404);
      assert.equal((await call(`/mentor/weeks/${weekId}/review`, "POST", { version: 4, action: "reviewed", feedback: "spoofed" }, foreignAccess)).status, 404);
      assert.equal((await call("/mentor/weeks", "GET", undefined, foreignAccess)).body.weeks.length, 0);
      await foreignMentor.destroy(); assert.equal((await call("/mentor/weeks", "GET", undefined, foreignAccess)).status, 401);
      await m.Mentor.create(foreignData);
    });
    await t.test("injected history failure rolls back weekly review and preserves frozen snapshot", async () => {
      for (const d of ["2026-09-28", "2026-09-29", "2026-09-30", "2026-10-01", "2026-10-02", "2026-10-03", "2026-10-04"]) await service.save(b.id, d, work, true);
      const submitted = await service.submit(b.id, "2026-09-28", { version: 0 }); const before = (await m.InternshipWeek.findByPk(submitted.submission.id)).toJSON();
      m.InternshipWeekEvent.addHook("afterCreate", "injectedHistoryFailure", () => { throw Error("Injected history failure"); });
      try { await assert.rejects(service.review(submitted.delivery.token, before.id, { version: 1, action: "reviewed", feedback: "fixture" }), /Injected history failure/); } finally { m.InternshipWeekEvent.removeHook("afterCreate", "injectedHistoryFailure"); }
      assert.deepEqual((await m.InternshipWeek.findByPk(before.id)).toJSON(), before); assert.equal(await m.InternshipWeekEvent.count({ where: { week_id: before.id } }), 1);
    });
    await t.test("last partial week requires applicable days only; incomplete current week cannot submit early", async () => { const result = await service.overview(a.id, "2026-10-05"); assert.equal(result.required_dates.length, 4); const early = require("../src/services/internshipLog.service").createInternshipLogService(m, { now: () => new Date("2026-10-07T12:00:00+07:00") }); await assert.rejects(early.submit(a.id, "2026-10-05", { version: 0 }), e => e.code === "WEEK_INCOMPLETE"); for (const date of result.required_dates) await service.save(a.id, date, work, true); assert.equal((await service.submit(a.id, "2026-10-05", { version: 0 })).submission.snapshot.logs.length, 4); });
    await t.test("email failure preserves submitted week with truthful delivery result", async () => { failEmail = true; const result = await call("/mentor-link", "POST", {}); assert.equal(result.status, 200); assert.equal(result.body.email_sent, false); assert.equal(await m.InternshipWeek.count({ where: { student_id: a.id } }), 2); });
    await t.test("SQL unique/FK/check and reviewed transition reject bypasses", async () => { await assert.rejects(m.InternshipDailyLog.create({ student_id: b.id, log_date: "2026-09-24", kind: "working", version: 1 }), /check constraint/); await assert.rejects(m.InternshipDailyLog.create({ student_id: crypto.randomUUID(), log_date: "2026-09-24", kind: "non_working", non_working_reason: "ลา", version: 1 }), /foreign key/); await assert.rejects(db.query("UPDATE internship_weeks SET status='submitted',version=version+1 WHERE id=:id", { replacements: { id: weekId } }), /transition/); assert.equal((await requestA.reload()).status, "approved"); assert.equal(await m.StudentFile.count(), 0); });
  } finally { if (server) await new Promise(resolve => server.close(resolve)); await db.close(); }
});
