const test = require("node:test"), assert = require("node:assert/strict");
const R = require("../src/services/supervisionRules");
const now = new Date("2026-10-08T12:00:00+07:00");
const input = { date: "2026-11-01", time: "09:30", mentor_verified_at: now.toISOString(), notes: " hello " };
test("Bangkok schedule converts explicit local time to UTC", () => { const row = R.schedule(input, now); assert.equal(row.scheduled_at.toISOString(), "2026-11-01T02:30:00.000Z"); assert.equal(row.notes, "hello"); });
test("impossible dates, time, past and absent mentor check rejected", () => { for (const patch of [{ date: "2026-02-30" }, { date: "2026-13-01" }, { date: "2026-10-08", time: "11:59" }, { time: "24:00" }, { time: "9:30" }, { mentor_verified_at: null }]) assert.throws(() => R.schedule({ ...input, ...patch }, now)); });
test("actor identities, status and unknown fields cannot enter appointment input", () => { for (const field of ["teacher_id", "student_id", "mentor_id", "status", "confirmed_at", "snapshot"]) assert.throws(() => R.schedule({ ...input, [field]: "spoof" }, now), e => e.code === "INVALID_INPUT"); });
test("substitute requires complete personal information and reason", () => { const substitute = { email: "fixture@example.invalid", first_name: "New", last_name: "Mentor", position: "Engineer", reason: "original unavailable" }; assert.equal(R.schedule({ ...input, substitute }, now).substitute.email, substitute.email); for (const key of Object.keys(substitute)) assert.throws(() => R.schedule({ ...input, substitute: { ...substitute, [key]: "" } }, now)); assert.throws(() => R.schedule({ ...input, substitute: { ...substitute, email: "invalid" } }, now)); });
test("input objects, UUIDs and length limits are validated", () => { for (const value of [null, [], "body"]) assert.throws(() => R.body(value, [])); for (const id of ["x", "00000000-0000-0000-0000-000000000000"]) assert.throws(() => R.uuid(id)); assert.throws(() => R.text("x".repeat(2001))); });
