const assert = require('node:assert/strict'), fs = require('node:fs/promises'), path = require('node:path');
module.exports = async function({ t,m,owner,staff,password,staffToken,api,ok,frontendUrl,browser,evaluate,value,click,wait,until,artifactRoot,runtimeErrors }) {
  const field = async (name,input) => evaluate(`(()=>{const e=document.querySelector('#activityForm [name='+${JSON.stringify(name)}+']');e.value=${JSON.stringify(input)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  const loaded = new Set(); browser.on('Page.lifecycleEvent', event => { if (event.name === 'DOMContentLoaded') loaded.add(event.loaderId); }); await browser.send('Page.setLifecycleEventsEnabled', { enabled:true });
  const navigate = async url => { const blank = await browser.send('Page.navigate',{url:'about:blank'}); if(blank.loaderId) await until(()=>loaded.has(blank.loaderId),'fresh calendar document',45000); const page = await browser.send('Page.navigate',{url}); if(page.loaderId) await until(()=>loaded.has(page.loaderId),'calendar document modules ready',45000); };
  const confirm = async () => { await wait("!!document.querySelector('.app-confirm-overlay:not(.is-leaving) .app-confirm-modal__confirm')",'calendar confirmation'); await click('.app-confirm-overlay:not(.is-leaving) .app-confirm-modal__confirm'); await wait("!document.querySelector('.app-confirm-overlay:not(.is-leaving)')",'calendar save'); await wait("!document.getElementById('activityRefresh').disabled",'calendar read-back'); };
  const capture = async name => { const result=await browser.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true}); await fs.writeFile(path.join(artifactRoot,name),Buffer.from(result.data,'base64')); };
  let row;
  await t.test('Staff real login, existing documents navigation and independent monthly calendar',async()=>{
    await navigate(`${frontendUrl}/staff-login.html`); await wait("!!document.getElementById('staffLoginForm')",'Staff login'); await value('staffEmail',staff.email); await value('staffPassword',password); await click('#staffLoginForm button[type=submit]');
    await wait("location.pathname.includes('department_staff') && !document.getElementById('activityRefresh')?.disabled",'Staff dashboard');
    await click('a[href="#activities"]'); assert.equal(await evaluate("document.getElementById('documents').hidden"),true); await value('activityMonth','2026-11'); await wait("!document.getElementById('activityRefresh').disabled",'month refresh complete'); await click('#activityFilters button[type=submit]'); await wait("document.querySelectorAll('.activity-day:not(.activity-blank)').length===30",'November grid');
    assert.match(await evaluate("document.getElementById('activityMessage').textContent"),/ยังไม่มี/); assert.equal(await evaluate("document.querySelectorAll('a[href=\"#documents\"]').length"),1);
  });
  await t.test('Create draft through confirmation; persisted actor, Bangkok timestamps and private snapshot',async()=>{
    await click('#activityNew'); await field('title','Browser calendar orientation'); await field('description','Public fixture description'); await field('starts_at','2026-11-02T09:30'); await field('ends_at','2026-11-02T12:00'); await field('location','Browser Room'); await field('internal_notes','Private browser calendar note'); await click('#activitySave');
    assert.equal(await m.CoopActivity.count(),0); await confirm(); row=await m.CoopActivity.findOne(); assert.equal(row.created_by,staff.id); assert.equal(row.starts_at.toISOString(),'2026-11-02T02:30:00.000Z'); assert.equal(row.status,'draft'); assert.equal(await m.CoopActivityHistory.count(),1); assert.match(await evaluate("document.getElementById('activityDetailBody').textContent"),/Private browser calendar note/);
  });
  await t.test('Invalid date range shows backend error and preserves form for correction',async()=>{
    await click('#activityNew'); await field('title','Invalid range'); await field('starts_at','2026-11-03T12:00'); await field('ends_at','2026-11-03T09:00'); await click('#activitySave'); await click('.app-confirm-overlay:not(.is-leaving) .app-confirm-modal__confirm');
    await wait("document.querySelector('.app-confirm-modal__error')?.textContent.includes('เวลาสิ้นสุด')",'date error'); assert.equal(await m.CoopActivity.count(),1); await click('.app-confirm-overlay:not(.is-leaving) .app-confirm-modal__cancel'); await wait("!document.getElementById('activityRefresh').disabled",'modal closed'); await click('#activityDiscard');
  });
  await t.test('Edit and publish retains original snapshot and reason, renders history',async()=>{
    await click('#activityActions button'); await field('status','published'); await field('reason','Publish official activity information'); await field('description','Updated public fixture'); await click('#activitySave'); await confirm(); await row.reload(); assert.equal(row.version,2); assert.equal(row.status,'published');
    const history=await m.CoopActivityHistory.findAll({order:[['version','ASC']]}); assert.equal(history[0].snapshot.status,'draft'); assert.equal(history[1].reason,'Publish official activity information'); assert.equal(await evaluate("document.querySelectorAll('#activityHistory details').length"),2);
  });
  await t.test('Chronological list search/category/date filters and detail work with real API',async()=>{
    await value('activityView','list'); await wait("document.querySelectorAll('#activityResults article').length===1",'activity list'); await value('activitySearch','notfound'); await click('#activityFilters button[type=submit]'); await wait("document.getElementById('activityMessage').textContent.includes('ยังไม่มี')",'empty search');
    await value('activitySearch','Browser calendar'); await value('activityCategory','orientation'); await value('activityFrom','2026-11-01'); await value('activityTo','2026-11-02'); await click('#activityFilters button[type=submit]'); await wait("document.querySelectorAll('#activityResults article').length===1",'filtered activity'); await click('#activityResults article button'); await wait("!document.getElementById('activityDetail').hidden",'detail');
  });
  await t.test('Concurrent external edit causes stale UI save rejection with no lost update',async()=>{
    await click('#activityActions button'); await field('description','Stale browser change'); await field('reason','Stale attempt');
    const body={title:row.title,description:'External current update',category:row.category,starts_at:'2026-11-02T09:30+07:00',ends_at:'2026-11-02T12:00+07:00',location:row.location,internal_notes:row.internal_notes,meeting_url:row.meeting_url,status:'published',version:2,reason:'Other session correction'};
    await ok(api(`/api/coop-activities/staff/${row.id}`,staffToken,body,'PUT')); await click('#activitySave'); await click('.app-confirm-overlay:not(.is-leaving) .app-confirm-modal__confirm'); await wait("document.querySelector('.app-confirm-modal__error')?.textContent.includes('ข้อมูลเปลี่ยนแล้ว')",'stale error'); await row.reload(); assert.equal(row.description,'External current update'); assert.equal(row.version,3);
    await click('.app-confirm-overlay:not(.is-leaving) .app-confirm-modal__cancel'); await wait("!document.getElementById('activityRefresh').disabled",'stale modal closed'); await click('#activityDiscard'); await click('#activityRefresh'); await wait("document.querySelectorAll('#activityResults article').length===1",'current list'); await click('#activityResults article button'); await wait("!document.getElementById('activityDetail').hidden",'current detail');
  });
  await t.test('Cancellation requires reason; canceled information/history remain available',async()=>{
    await click('#activityActions button:last-child'); await evaluate("document.querySelector('.app-confirm-modal__reason textarea').value='Venue canceled privately'"); await confirm(); await row.reload(); assert.equal(row.status,'canceled'); assert.equal(row.version,4); assert.equal(await m.CoopActivityHistory.count(),4); assert.equal(await evaluate("document.querySelectorAll('#activityActions button').length"),0); await capture('calendar-staff-desktop.png');
  });
  await t.test('Student real login read-only calendar hides drafts, Staff notes and cancellation reasons',async()=>{
    await ok(api('/api/coop-activities/staff',staffToken,{title:'Hidden draft browser',category:'other',starts_at:'2026-11-02T08:00+07:00',ends_at:'2026-11-02T09:00+07:00',status:'draft',creation_key:require('node:crypto').randomUUID()}));
    await navigate(`${frontendUrl}/login.html`); await wait("!!document.getElementById('loginForm')",'Student login'); await value('loginEmail',owner.student.email); await value('loginPassword',password); await click('#loginForm button[type=submit]'); await wait("location.pathname.includes('student_coop') && !!document.getElementById('activityMonth') && !document.getElementById('activityRefresh').disabled",'Student calendar ready');
    await click('[data-target="panel-activities"]'); await value('activityMonth','2026-11'); await wait("!document.getElementById('activityRefresh').disabled",'month refresh complete'); await click('#activityFilters button[type=submit]'); await wait("document.querySelectorAll('.activity-event').length===1",'published canceled activity'); await click('.activity-event'); await wait("!document.getElementById('activityDetail').hidden",'Student detail');
    const text=await evaluate("document.getElementById('panel-activities').textContent"); assert.match(text,/ยกเลิก/); assert.ok(!text.includes('Private browser calendar note')); assert.ok(!text.includes('Venue canceled privately')); assert.ok(!text.includes('Hidden draft browser')); assert.equal(await evaluate("!!document.getElementById('activityNew') || !!document.getElementById('activityForm')"),false);
  });
  await t.test('Student mobile monthly/list views fit viewport and retain full readable details',async()=>{
    await browser.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); assert.ok(await evaluate('document.documentElement.scrollWidth<=391'),'Student calendar overflow'); await capture('calendar-student-mobile.png');
    await value('activityView','list'); await wait("document.querySelectorAll('#activityResults article').length===1",'mobile list'); assert.ok(await evaluate('document.documentElement.scrollWidth<=391'),'Student activity list overflow');
  });
  await t.test('Real offline error clears stale results and refresh recovers',async()=>{
    await browser.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:-1,uploadThroughput:-1}); await click('#activityRefresh'); await wait("document.getElementById('activityMessage').textContent.includes('Unable to connect')",'offline error'); assert.equal(await evaluate("document.querySelectorAll('#activityResults article').length"),0);
    await browser.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1}); await click('#activityRefresh'); await wait("document.querySelectorAll('#activityResults article').length===1",'offline recovery');
  });
  await t.test('Staff mobile layout and existing document navigation remain available',async()=>{
    await navigate(`${frontendUrl}/src/department_staff/department_staff.html#activities`); await wait("!!document.getElementById('activityView') && !document.getElementById('activityRefresh').disabled",'Staff mobile calendar'); await value('activityMonth','2026-11'); await wait("!document.getElementById('activityRefresh').disabled",'month refresh complete'); await click('#activityFilters button[type=submit]'); await wait("document.querySelectorAll('.activity-event').length===2",'Staff mobile events'); assert.ok(await evaluate('document.documentElement.scrollWidth<=391'),'Staff calendar overflow'); 
    const geometry = await evaluate("(()=>{window.scrollTo({top:0,behavior:'instant'});return {header:document.querySelector('.navbar').getBoundingClientRect().bottom,menu:document.querySelector('.dashboard-sidebar').getBoundingClientRect().top};})()");
    assert.ok(geometry.header<=geometry.menu+1,`Staff navbar must not overlap menu: ${JSON.stringify(geometry)}`); await capture('calendar-staff-mobile.png');
    await click('a[href="#documents"]'); assert.equal(await evaluate("document.getElementById('documents').hidden"),false); assert.equal(await evaluate("document.getElementById('activities').hidden"),true);
  });
  await t.test('No unexpected application JavaScript errors',()=>{assert.deepEqual(runtimeErrors,[]);});
};
