const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
module.exports = async function ({ t,m,owner,otherOwner,project,teacher,password,api,projectToken,frontendUrl,browser,evaluate,value,click,wait,pause,artifactRoot,runtimeErrors,consoleErrors,failedResponses,navigate,teacherPage,confirm,service,first,second }) {
  let failed = false, oldImage, result;
  const scenario = (name, fn) => t.test(name, { skip: failed }, async () => { try { await fn(); } catch(error) { failed=true; console.log('Result diagnostic:', await evaluate("JSON.stringify({path:location.pathname,messages:[...document.querySelectorAll('.supervision-result-message')].map(n=>n.textContent),modal:document.querySelector('.app-confirm-modal__error')?.textContent})")); throw error; } });
  const panel = visit => `#supervisionAppointments article:nth-child(${visit}) .supervision-result`;
  async function open(visit) { await click(`[data-result-visit="${visit}"]`); await wait(`!!document.getElementById('result_${visit}_summary') && !document.querySelector('${panel(visit)} > button').disabled && !document.querySelector('${panel(visit)} .supervision-result-message').textContent.includes('กำลังโหลด')`, 'result editor loaded'); }
  async function save(visit) { await click(`${panel(visit)} form button[type=submit]`); await wait(`document.querySelector('${panel(visit)} .supervision-result-message').textContent.includes('ฉบับ') && !document.querySelector('${panel(visit)} form button').disabled`, 'result draft committed'); }
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2K0cAAAAASUVORK5CYII=';
  async function upload(visit,slot,name='proof.png',type='image/png',bytes=png) { await evaluate(`(()=>{ const canvas=document.createElement('canvas');canvas.width=320;canvas.height=160;const ctx=canvas.getContext('2d');ctx.fillStyle=${JSON.stringify(slot===1?'#dbeafe':'#dcfce7')};ctx.fillRect(0,0,320,160);ctx.fillStyle='#0f172a';ctx.font='20px sans-serif';ctx.fillText('Fixture evidence ${visit}.${slot}',24,64);ctx.font='14px sans-serif';ctx.fillText(${JSON.stringify(name)},24,100);const encoded=${JSON.stringify(bytes===png)}?canvas.toDataURL('image/png').split(',')[1]:${JSON.stringify(bytes)};const input=document.getElementById('result_${visit}_image_${slot}'), data=new DataTransfer(), bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)); data.items.add(new File([bytes],${JSON.stringify(name)},{type:${JSON.stringify(type)}}));input.files=data.files;input.dispatchEvent(new Event('change',{bubbles:true})); })()`); }
  async function complete(visit) { await click(`${panel(visit)} .supervision-actions button:first-child`); await confirm(); await wait(`document.querySelector('${panel(visit)} .supervision-result-message').textContent.includes('เสร็จสมบูรณ์')`,'completed result'); }
  async function capture(name) { await evaluate("document.querySelectorAll('.app-toast__close').forEach(n=>n.click());document.querySelector('.supervision-result')?.scrollIntoView()"); await pause(250); const shot=await browser.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true}); await fs.writeFile(path.join(artifactRoot,name),Buffer.from(shot.data,'base64')); }
  await scenario('Results: original Mentor confirms rescheduled appointment before recording',async()=>{
    await browser.send('Emulation.clearDeviceMetricsOverride'); await first.reload(); const delivery=await service.resend(project.id,owner.student.id,first.id,{version:first.version}); await navigate(`${frontendUrl}/src/mentor_coop/mentor_verify_user.html#appointment_token=${delivery.token}`); await wait("!document.getElementById('mentorAppointmentConfirm').disabled",'original appointment ready'); await click('#mentorAppointmentIdentity'); await click('#mentorAppointmentConfirm'); await confirm(); await wait("document.getElementById('mentorAppointmentActions').hidden",'original confirmed'); await first.reload(); assert.equal(first.status,'confirmed');
  });
  await scenario('Results: visit 1 incomplete draft saves and missing evidence cannot complete',async()=>{
    await teacherPage(); await open(1); await value('result_1_summary','Browser descriptive outcome'); await save(1); result=await m.SupervisionResult.findOne({where:{appointment_id:first.id}}); assert.equal(result.status,'draft'); assert.equal(result.version,1); await click(`${panel(1)} .supervision-actions button:first-child`); assert.match(await evaluate(`document.querySelector('${panel(1)} .supervision-result-message').textContent`),/สองภาพ/); assert.equal(await evaluate("!!document.querySelector('.app-confirm-overlay:not(.is-leaving)')"),false);
  });
  await scenario('Results: invalid image rejected; two private image previews save and survive reload',async()=>{
    await upload(1,1,'invalid.svg','image/svg+xml'); assert.match(await evaluate(`document.querySelector('${panel(1)} .supervision-result-message').textContent`),/PNG/); await value('result_1_visited_on','2026-11-05'); await value('result_1_issues','No observed issues'); await value('result_1_recommendations','Follow up next visit'); await upload(1,1); await upload(1,2,'proof-2.png'); assert.equal(await evaluate(`document.querySelectorAll('${panel(1)} fieldset img:not([hidden])').length`),2); await save(1); await wait(`document.querySelectorAll('${panel(1)} .supervision-result-readback img').length===2 && [...document.querySelectorAll('${panel(1)} .supervision-result-readback img')].every(n=>n.complete && n.naturalWidth>0)`,'saved private images decoded'); await result.reload(); oldImage=result.image_1_id; assert.ok(oldImage && result.image_2_id);
    await teacherPage(); await open(1); await wait(`document.querySelectorAll('${panel(1)} .supervision-result-readback img').length===2 && [...document.querySelectorAll('${panel(1)} .supervision-result-readback img')].every(n=>n.naturalWidth>0)`,'private images after refresh'); assert.equal(await evaluate("document.getElementById('result_1_summary').value"),'Browser descriptive outcome');
    await browser.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); assert.ok(await evaluate('document.documentElement.scrollWidth<=391'),'editable result form fits 390px'); await capture('teacher-result-draft-mobile.png'); await browser.send('Emulation.clearDeviceMetricsOverride');
  });
  await scenario('Results: image replacement retains earlier revision and authenticated historical evidence',async()=>{
    await upload(1,1,'replacement.png'); await save(1); await result.reload(); assert.notEqual(result.image_1_id,oldImage); const revisions=await m.SupervisionResultRevision.findAll({where:{result_id:result.id},order:[['version','ASC']]}); assert.equal(revisions[1].snapshot.image_1_id,oldImage); assert.equal(await m.SupervisionImage.count({where:{appointment_id:first.id}}),3); await click(`${panel(1)} .supervision-result-history details:nth-child(2) summary`); await wait(`document.querySelectorAll('${panel(1)} .supervision-result-history details:nth-child(2) img').length===2 && [...document.querySelectorAll('${panel(1)} .supervision-result-history details:nth-child(2) img')].every(n=>n.naturalWidth>0)`,'historical images decoded');
  });
  await scenario('Results: completed visit 1 is frozen; protected appointment cannot reschedule',async()=>{
    await complete(1); await result.reload(); assert.equal(result.status,'completed'); assert.equal(await evaluate(`document.querySelector('${panel(1)} fieldset').disabled`),true); const res=await api(`/api/supervision/teacher/students/${owner.student.id}/visits/1`,projectToken,{date:'2026-11-06',time:'09:30',mentor_verified_at:first.snapshot.original_mentor.verified_at,version:first.version,reason:'Fixture blocked reschedule'},'PUT'); assert.equal(res.status,409); assert.equal(res.data.code,'APPOINTMENT_HAS_RESULT');
  });
  await scenario('Results: visit 2 uses its own appointment and two independent images',async()=>{
    await open(2); await value('result_2_visited_on','2026-12-04'); await value('result_2_summary','Second visit descriptive outcome'); await upload(2,1,'second-1.png'); await upload(2,2,'second-2.png'); await save(2); await complete(2); const row=await m.SupervisionResult.findOne({where:{appointment_id:second.id}}); assert.equal(row.status,'completed'); assert.equal(row.snapshot.appointment.visit_number,2); assert.equal(row.snapshot.appointment.snapshot.attending_mentor.first_name,'Browser Substitute'); assert.notEqual(row.image_1_id,result.image_1_id);
  });
  await scenario('Results: Teacher desktop/mobile form and persisted photos fit 390px viewport',async()=>{
    await capture('teacher-results-desktop.png'); await browser.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); assert.ok(await evaluate('document.documentElement.scrollWidth<=391')); await capture('teacher-results-mobile.png');
  });
  await scenario('Results: Student login reads completed results/photos with no editing controls',async()=>{
    await navigate(`${frontendUrl}/login.html`); await value('loginEmail',owner.student.email); await value('loginPassword',password); await click('#loginForm button[type=submit]'); await wait("document.querySelectorAll('#studentSupervisionAppointments > article').length===2",'Student supervision results'); await click('[data-result-visit="1"]'); await wait("document.querySelector('#studentSupervisionAppointments .supervision-result-message').textContent.includes('เสร็จสมบูรณ์')",'Student completed result'); await wait("[...document.querySelectorAll('#studentSupervisionAppointments .supervision-result img')].filter(n=>n.naturalWidth>0).length===2",'Student private photos'); assert.equal(await evaluate("document.querySelectorAll('#studentSupervisionAppointments .supervision-result input,#studentSupervisionAppointments .supervision-result textarea').length"),0); assert.ok(await evaluate('document.documentElement.scrollWidth<=391')); await capture('student-results-mobile.png');
  });
  await scenario('Results: anonymous/foreign Student image access denied; no private paths exposed',async()=>{
    const own=`/api/supervision/student/appointments/${first.id}/visits/1/result`, view=await api(own,owner.token); assert.equal(view.status,200); assert.equal(view.data.images.length,2); assert.ok(!JSON.stringify(view.data).includes('storage_path')); assert.equal((await api(own,otherOwner.token)).status,404); assert.equal((await api(own+'/images/'+result.image_1_id,null)).status,401); assert.equal((await api(own+'/images/'+oldImage,owner.token)).status,404);
  });
  await scenario('Results: offline refresh reports failure and recovers real result readback',async()=>{
    await teacherPage(); await open(1); await browser.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:-1,uploadThroughput:-1}); await click(`${panel(1)} .supervision-actions button:last-child`); await wait(`document.querySelector('${panel(1)} .supervision-result-message').textContent.includes('Unable to connect')`,'offline result feedback'); await browser.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1}); await click(`${panel(1)} .supervision-actions button:last-child`); await wait(`document.querySelector('${panel(1)} .supervision-result-message').textContent.includes('เสร็จสมบูรณ์')`,'result network recovery');
  });
  await scenario('Results: no runtime errors; two completed results, immutable history and unrelated data preserved',async()=>{
    assert.deepEqual(runtimeErrors,[]); assert.deepEqual(consoleErrors.filter(row=>row.source!=='network'),[]); assert.deepEqual(failedResponses.filter(row=>!row.url.endsWith('/favicon.ico') && !(row.status===409 && row.url.endsWith('/visits/1')) && !(row.status===410 && row.url.endsWith('/mentor/appointment'))),[]); assert.equal(await m.SupervisionResult.count(),2); assert.equal(await m.SupervisionResultRevision.count(),6); assert.equal(await m.StudentFile.count(),0); assert.equal((await m.CoopRequest.findByPk(owner.id)).status,'approved'); assert.equal((await owner.student.reload()).advisor_teacher_id,teacher.id); assert.equal(owner.student.coop_advisor_teacher_id,project.id);
  });
};
