// Development evidence template only. Official wording/signature/format await approval.
const TEMPLATE_VERSION = 'dev-letter-v1';
const TITLES = { cooperation: 'หนังสือขอความอนุเคราะห์รับนักศึกษาสหกิจศึกษา', placement: 'หนังสือส่งตัวนักศึกษา' };
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
function renderDevelopmentLetter(document) {
  const { snapshot: s, metadata: meta } = document;
  const pair = (label, value) => value ? `<dt>${escape(label)}</dt><dd>${escape(value)}</dd>` : '';
  return `<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escape(TITLES[document.document_type])}</title><style>body{font-family:Tahoma,sans-serif;line-height:1.8;max-width:760px;margin:32px auto;padding:24px;color:#18282e}aside{border:2px solid #966800;padding:12px;background:#fff9e5}dl{display:grid;grid-template-columns:180px 1fr;gap:8px}dt{font-weight:bold}dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}h1{font-size:22px}@media print{body{margin:0;padding:16mm}aside{background:white}}@page{size:A4;margin:12mm}</style></head><body><aside>ฉบับตัวอย่างสำหรับทดสอบ — รูปแบบและข้อความเอกสารราชการยังต้องได้รับการยืนยัน ไม่ใช่เอกสารที่ออกอย่างเป็นทางการ</aside><h1>${escape(TITLES[document.document_type])}</h1><dl>${pair('เลขที่หนังสือ', document.document_number)}${pair('วันที่', meta.issue_date)}${pair('เรียน', s.request.letter_recipient_name)}${pair('ตำแหน่ง / หน่วยงานผู้รับ', s.request.letter_recipient_position_department)}${pair('สถานประกอบการ', s.request.company_name)}${pair('ที่อยู่', s.request.company_address)}${pair('จังหวัด', s.request.company_province)}${pair('นักศึกษา', `${s.student.first_name} ${s.student.last_name}`)}${pair('รหัสนักศึกษา', s.student.student_id)}${pair('สาขา', s.student.major)}${pair('ช่วงปฏิบัติงาน', `${s.request.work_start_date} – ${s.request.work_end_date}`)}${pair('Head อนุมัติเมื่อ', s.approval.head.approved_at)}${pair('ผู้ลงนาม (ข้อมูลร่าง)', meta.signatory_name)}${pair('ตำแหน่งผู้ลงนาม', meta.signatory_position)}${pair('หมายเหตุ', meta.notes)}</dl><small>Template ${escape(document.template_version)} · document ${escape(document.id)} · version ${escape(document.version)}</small></body></html>`;
}
module.exports = { TEMPLATE_VERSION, TITLES, renderDevelopmentLetter };
